# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_ENV_HINTS=TRUE

# my custom binaries
export PATH=$HOME/workspace/my-environment/bin:$PATH

# pyenv and virtualenvs
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
export PIP_REQUIRE_VIRTUALENV=true
