# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# my custom binaries
export PATH=$HOME/workspace/my-environment/bin:$PATH

# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# if command -v pyenv 1>/dev/null 2>&1; then
#   eval "$(pyenv init --path)"
# fi
